ANGER_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_anger_60k.txt"
ANTICIPATION_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_anticipation_60k.txt"
DISGUST_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_disgust_60k.txt"
FEAR_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_fear_60k.txt"
JOY_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_joy_60k.txt"
SADNESS_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_sadness_60k.txt"
SURPRISE_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_surprise_60k.txt"
TRUST_PATH = "C:/Users/Fazza/Desktop/materiale_maadb/messaggi_twitter/dataset_dt_trust_60k.txt"